# .github/workflows/ci.yml
name: Docker Post-Release Test

on:
  push:
    paths:
      - ".github/workflows/docker_post-release_test.yml"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env File
        run: touch .env && echo "PRINTER_TYPE=dummy" >> .env
      - name: Build and Test Docker Image
        run: |
          docker compose up -d
          sleep 10
          curl http://localhost:8000/ | grep "Printer API is running"
          docker compose down
